server:
  port: 9196
  
spring:
  application:
    name: CONFIG-SERVER  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitprajapati8396/config-server
          clone-on-start: true  
          
eureka:
  client:
    register-with-eureka: true    
    fetch-registry: true
    serviceUrl:  
      defaultZone: http://localhost:8761/eureka            