server:
  port: 9294
  
spring:
  application:
    name: CLOUD-GATEWAY
#  #config server   
#  
#  cloud:
#    config: 
#      enabled: true
#      uri: 
#      - http://localhost:9196
      
#eureka:
#  client:
#    register-with-eureka: true    
#    fetch-registry: true
#    serviceUrl:  
#      defaultZone: http://localhost:8761/eureka      
  
#adding all microservices details to the API Gateway    
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
          uri: http://localhost:9293
          predicates: 
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE 
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
#          uri: lb://DEPARTMENT-SERVICE
          uri: http://localhost:9292
          predicates: 
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack  

#Hystrix configuration                
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000     
            
#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
