#server port
server:
  port: 9293

#application name
spring:
  application:
    name: USER-SERVICE

#DB config
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb?currentSchema=public
    username: postgres
    password: Password@123
    driverClassName: org.postgresql.Driver 

   
 